-- TNCSC CRS — real user management
--
-- Until now users lived as a JSON blob in crs_state('global','userStore'), with
-- passwords in clear text, and the sign-in screen compared every password
-- against a single hardcoded literal. This moves users into a table of their
-- own, hashes the passwords, and makes the database the only thing that decides
-- whether a sign-in succeeds.
--
-- Run AFTER 0001_init.sql. It seeds itself from the existing userStore row, so
-- no user data has to be retyped.

-- Supabase keeps extensions in the `extensions` schema, not `public`. Every
-- security definer function below therefore pins `search_path = public,
-- extensions` — pinning it to `public` alone hides crypt() from inside the
-- function body, which LANGUAGE SQL rejects at creation time:
--   ERROR: function crypt(text, text) does not exist
create extension if not exists pgcrypto with schema extensions;

-- Same reason, for the seeding INSERT further down, which also calls crypt().
set search_path = public, extensions;

create table if not exists users (
  id            bigint generated by default as identity primary key,
  username      text        not null,
  full_name     text        not null default '',
  phone         text,
  email         text,
  role          text        not null,
  crs_id        integer,
  password_hash text        not null,
  active        boolean     not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Deliberately NOT unique. Two people share 'crs9' today (the shop's Bill Clerk
-- and its Packer), and the sign-in screen relies on that: typing a shop's
-- username offers a role picker when more than one person is registered for it.
-- Making this unique would silently break that flow. Uniqueness belongs on a
-- per-person identifier, which is a data decision, not a schema one.
create index if not exists users_username_idx on users (lower(username));
create index if not exists users_phone_idx    on users (phone);
create index if not exists users_crs_idx      on users (crs_id);

comment on table  users               is 'Application users. Passwords are bcrypt hashes via pgcrypto.';
comment on column users.username      is 'Not unique — a shop username can map to several staff (see users_username_idx).';
comment on column users.password_hash is 'crypt(password, gen_salt(''bf'')). Never select this column into a response.';

-- ── Seed from the existing userStore blob ───────────────────────────────────
insert into users (id, username, full_name, phone, email, role, crs_id, password_hash, active, created_at)
select
  (u->>'id')::bigint,
  u->>'username',
  coalesce(u->>'fullName', ''),
  nullif(u->>'phone', ''),
  nullif(u->>'email', ''),
  u->>'role',
  (u->>'crsId')::integer,
  crypt(coalesce(nullif(u->>'password', ''), 'pds123'), gen_salt('bf')),
  coalesce((u->>'active')::boolean, true),
  coalesce((u->>'createdAt')::timestamptz, now())
from crs_state, jsonb_array_elements(data) as u
where scope = 'global' and store_key = 'userStore'
on conflict (id) do nothing;

-- Keep the identity sequence ahead of the seeded ids.
select setval(
  pg_get_serial_sequence('users', 'id'),
  greatest(coalesce((select max(id) from users), 0), 1)
);

-- ── Sign-in ─────────────────────────────────────────────────────────────────
-- Comparing a bcrypt hash has to happen in the database, so this is the one
-- entry point the API uses. It returns every active account matching the
-- identifier, because a shop username can legitimately match two people and the
-- caller then asks which of them is signing in.
--
-- security definer so it can read users while RLS keeps the table otherwise
-- unreadable. It never returns password_hash.
create or replace function verify_login(p_identifier text, p_password text)
returns table (
  id bigint, username text, full_name text, phone text,
  email text, role text, crs_id integer
)
language sql
security definer
set search_path = public, extensions
as $$
  select u.id, u.username, u.full_name, u.phone, u.email, u.role, u.crs_id
  from users u
  where u.active
    and (lower(u.username) = lower(p_identifier) or u.phone = p_identifier)
    and u.password_hash = crypt(p_password, u.password_hash)
  order by u.id
$$;

-- PUBLIC first — PostgreSQL grants EXECUTE on new functions to PUBLIC by
-- default, and anon inherits it from there, so revoking the role by name alone
-- leaves the function world-callable. See 0003_lock_functions.sql.
revoke all on function verify_login(text, text) from public;
revoke all on function verify_login(text, text) from anon, authenticated;
grant execute on function verify_login(text, text) to service_role;

-- ── Password changes ────────────────────────────────────────────────────────
create or replace function set_user_password(p_user_id bigint, p_password text)
returns void
language sql
security definer
set search_path = public, extensions
as $$
  update users
     set password_hash = crypt(p_password, gen_salt('bf')),
         updated_at    = now()
   where id = p_user_id
$$;

revoke all on function set_user_password(bigint, text) from public;
revoke all on function set_user_password(bigint, text) from anon, authenticated;
grant execute on function set_user_password(bigint, text) to service_role;

-- ── RLS ─────────────────────────────────────────────────────────────────────
-- Same posture as crs_state: enabled with no policy, so the publishable key can
-- read nothing. All access goes through the route handlers, which hold the
-- secret key and authorise against the app's session cookie.
alter table users enable row level security;

-- ── Retire the old blob ─────────────────────────────────────────────────────
-- Kept under a renamed key rather than deleted, so the pre-migration user list
-- is still recoverable if anything about the seed looks wrong.
update crs_state
   set store_key = 'userStore__pre_0002'
 where scope = 'global' and store_key = 'userStore';
