-- TNCSC CRS — paid statement downloads with manual UPI settlement
--
-- Shop users pay per sheet before a statement can be previewed, printed or
-- exported; ADMIN keeps everything free. There is no payment gateway. The
-- customer pays into the office's own UPI handle, types the UTR back, and an
-- admin matches it against the bank feed and approves. That makes every row
-- here a record of a HUMAN decision, not a machine-verified transaction — the
-- audit columns (decided_by / decided_at) are the only thing standing behind
-- an approval, so they are not nullable once a decision is made.
--
-- Money is stored in PAISE as integers throughout. Never store rupees as a
-- float: 0.1 + 0.2 in a statutory fee ledger is not a rounding curiosity, it
-- is a reconciliation failure against the bank statement.
--
-- Run AFTER 0003_lock_functions.sql.

-- ── Settings ────────────────────────────────────────────────────────────────
-- Deliberately a TABLE and not a `__config` row in crs_state. Any signed-in
-- user can POST to /api/state and write crs_state; putting the payee VPA there
-- would let a shop user redirect every payment to their own handle. This table
-- is only ever written through /api/payments/settings, which is admin-only.
create table if not exists payment_settings (
  id                    smallint    primary key default 1 check (id = 1),
  enabled               boolean     not null default false,
  upi_vpa               text        not null default '',
  upi_payee_name        text        not null default '',
  -- ₹40 per sheet, INCLUSIVE of GST (the customer pays exactly ₹40).
  statement_sheet_paise integer     not null default 4000 check (statement_sheet_paise >= 0),
  -- ₹5 per day, PLUS GST (the customer pays ₹5 + tax).
  dss_day_paise         integer     not null default 500  check (dss_day_paise >= 0),
  -- Basis points, so 18% is 1800 and no fraction is lost to a numeric type.
  gst_rate_bp           integer     not null default 1800 check (gst_rate_bp between 0 and 10000),
  updated_at            timestamptz not null default now(),
  updated_by            text        not null default ''
);

insert into payment_settings (id) values (1) on conflict (id) do nothing;

comment on table  payment_settings                is 'Single-row payment configuration. Admin-only writes via /api/payments/settings.';
comment on column payment_settings.upi_vpa        is 'Payee VPA. Kept out of crs_state so a shop user cannot redirect payments.';
comment on column payment_settings.gst_rate_bp    is 'GST rate in basis points (1800 = 18%).';

-- ── Orders ──────────────────────────────────────────────────────────────────
create sequence if not exists payment_order_no_seq;

create table if not exists payment_orders (
  id             bigint      generated by default as identity primary key,
  -- Human-facing reference the customer quotes to the office. Defaulted from a
  -- sequence rather than built in the route handler: two shops ordering in the
  -- same millisecond must not race for the same number.
  order_no       text        not null unique
                 default 'PAY-' || to_char(now(), 'YYYYMMDD') || '-'
                                || lpad(nextval('payment_order_no_seq')::text, 5, '0'),
  -- Who asked. Denormalised name/username so the admin queue reads correctly
  -- even after a user is renamed or deactivated.
  user_id        bigint      not null,
  username       text        not null default '',
  full_name      text        not null default '',
  -- The SHOP the entitlement belongs to. Entitlement is per shop, not per
  -- person: crs9's Bill Clerk and Packer are two users behind one shop, and
  -- charging the same shop twice for one month's statements would be wrong.
  crs_id         integer     not null,
  kind           text        not null check (kind in ('statement', 'dss')),
  month          smallint    not null check (month between 1 and 12),
  year           smallint    not null check (year between 2000 and 2200),
  -- Statement orders: the section ids paid for. DSS orders: empty.
  section_ids    jsonb       not null default '[]'::jsonb,
  sheet_count    integer     not null default 0 check (sheet_count >= 0),
  day_count      integer     not null default 0 check (day_count >= 0),
  -- Prices as quoted at order time. Frozen deliberately: changing the tariff
  -- must not retroactively alter what someone already paid.
  base_paise     integer     not null check (base_paise >= 0),
  gst_paise      integer     not null check (gst_paise >= 0),
  total_paise    integer     not null check (total_paise >= 0),
  gst_rate_bp    integer     not null,
  gst_inclusive  boolean     not null,
  status         text        not null default 'pending'
                             check (status in ('pending', 'awaiting_approval', 'approved', 'rejected')),
  utr            text,
  reject_reason  text,
  created_at     timestamptz not null default now(),
  submitted_at   timestamptz,
  decided_at     timestamptz,
  decided_by     bigint,
  decided_by_name text,
  -- An approved or rejected row must say who decided and when. Without this a
  -- bad approval is untraceable, and the whole control is the human.
  constraint payment_orders_decided_ck check (
    status not in ('approved', 'rejected')
    or (decided_at is not null and decided_by is not null)
  )
);

create index if not exists payment_orders_status_idx on payment_orders (status, created_at desc);
create index if not exists payment_orders_user_idx   on payment_orders (user_id, created_at desc);
-- The entitlement lookup: "is there an approved order for this shop/month?"
create index if not exists payment_orders_scope_idx
  on payment_orders (crs_id, kind, year, month) where status = 'approved';

comment on table  payment_orders             is 'Per-download fee orders settled manually over UPI and approved by an admin.';
comment on column payment_orders.crs_id      is 'Entitlement is per SHOP — one shop, several staff, one payment.';
comment on column payment_orders.total_paise is 'Paise, not rupees. Reconciled against the bank feed by hand.';

-- Same posture as every other table in this schema: RLS on, no permissive
-- policy, all access through route handlers holding the secret key. The app
-- has its own login rather than Supabase Auth, so there is no auth.uid() to
-- write a policy against.
alter table payment_settings enable row level security;
alter table payment_orders   enable row level security;
