-- TNCSC CRS — notifications: approval alerts, approval results, admin messages
--
-- One mechanism for every "somebody has to look at this" in the system. A shop
-- raising a payment or a clear request notifies the administrators; an
-- administrator's decision notifies whoever asked; an administrator's message
-- reaches the shops it is addressed to. Future approval modules call the same
-- service and need no schema change.
--
-- WHY TWO TABLES. A message is written once and read by many people, and the
-- office needs to know exactly who read it and when. So the content lives in
-- `notifications` and each person's copy — delivered, opened, read,
-- acknowledged — lives in its own row in `notification_recipients`. Read
-- tracking is then one row per person rather than a list inside a blob that
-- sixty people would all be rewriting at once.
--
-- WHY RECIPIENTS ARE RESOLVED AT SEND TIME. Name, role and shop are copied onto
-- the recipient row, like payment_orders.full_name. A Packer transferred from
-- CRS 7 to CRS 19 next month still appears under CRS 7 in the read report for a
-- message CRS 7 received — which is what the report is a record of.
--
-- Run AFTER 0004_payments.sql. Until it is run, the app keeps working: every
-- approval workflow proceeds exactly as before, and notifications are skipped.

create table if not exists notifications (
  id                  bigint      generated by default as identity primary key,
  type                text        not null check (type in (
                        'PAYMENT_REQUEST', 'CLEAR_REQUEST', 'EDIT_REQUEST', 'DELETE_REQUEST',
                        'DATA_CORRECTION_REQUEST', 'DOWNLOAD_APPROVAL', 'OTHER_APPROVAL',
                        'APPROVAL_RESULT', 'MESSAGE', 'SYSTEM'
                      )),
  -- The filter an administrator sees it under. Stored rather than derived in a
  -- query so the per-person list can be filtered on an index.
  category            text        not null check (category in ('payments', 'clear', 'approvals', 'messages', 'system')),
  title               text        not null,
  message             text        not null default '',
  -- Structured lines ("Requested By" → "Divya (BC)") rendered by the viewer.
  -- Dates stay ISO here and are formatted in the reader's own time zone, so a
  -- server running in UTC never prints the wrong hour on an IST screen.
  details             jsonb       not null default '[]'::jsonb,
  priority            text        not null default 'normal' check (priority in ('normal', 'important', 'urgent')),
  -- For an approval request, where the request stands. Updated when it is
  -- decided, so an administrator's bell stops saying "pending" about something
  -- a colleague already approved.
  status              text        not null default 'open',
  -- Who raised it. For an approval request this IS the requester, which is how
  -- a decision finds the person to tell — for every module, without each one
  -- having to remember its own requester column.
  sender_user_id      bigint,
  sender_name         text        not null default '',
  related_request_id  text,
  related_module      text,
  related_crs_id      integer,
  -- App-relative path to the record. Built server-side, never taken from input.
  link                text,
  -- For a message: how its recipients were chosen, for the sent list.
  audience            jsonb       not null default '{}'::jsonb,
  -- Important and urgent messages must be acknowledged, not merely seen.
  requires_ack        boolean     not null default false,
  created_at          timestamptz not null default now()
);

create index if not exists notifications_request_idx on notifications (related_module, related_request_id);
create index if not exists notifications_sent_idx    on notifications (type, created_at desc);

create table if not exists notification_recipients (
  id                  bigint      generated by default as identity primary key,
  notification_id     bigint      not null references notifications (id) on delete cascade,
  recipient_user_id   bigint      not null,
  recipient_crs_id    integer,
  recipient_name      text        not null default '',
  recipient_role      text        not null default '',
  -- Copied from the notification so a person's own list is one indexed table.
  category            text        not null,
  created_at          timestamptz not null default now(),
  -- First time this person's screen actually received it.
  delivered_at        timestamptz,
  -- First time they opened it.
  opened_at           timestamptz,
  -- When they read it — by opening it, or by marking it read. Signing in alone
  -- does not count, and neither does a popup appearing on its own.
  read_at             timestamptz,
  acknowledged_at     timestamptz,
  is_read             boolean     not null default false,
  -- One copy per person per notification, so a retried send cannot double up.
  unique (notification_id, recipient_user_id)
);

-- The bell: "how many unread for me", and "my latest, newest first".
create index if not exists notification_recipients_inbox_idx
  on notification_recipients (recipient_user_id, is_read, created_at desc);
create index if not exists notification_recipients_category_idx
  on notification_recipients (recipient_user_id, category, created_at desc);
-- The read report for one message.
create index if not exists notification_recipients_notification_idx
  on notification_recipients (notification_id);

comment on table notifications           is 'Approval alerts, approval results and admin messages. Written only by route handlers.';
comment on table notification_recipients is 'One row per person per notification: delivered, opened, read and acknowledged times.';
comment on column notification_recipients.read_at is 'Set only when the person opens it or marks it read — never on sign-in.';

-- Same posture as every table in this schema: RLS on, no permissive policy,
-- every read and write through route handlers holding the secret key. The app
-- keeps its own login rather than Supabase Auth, so there is no auth.uid() to
-- write a policy against — and that is also why the browser does not subscribe
-- to these tables directly (see src/lib/notify/client.ts).
alter table notifications           enable row level security;
alter table notification_recipients enable row level security;

-- The inbox query embeds a notification in each recipient row through the
-- foreign key above. PostgREST only learns that relationship when its schema
-- cache reloads; without this the bell can answer "could not find a
-- relationship" until something else happens to trigger a reload.
notify pgrst, 'reload schema';
