-- TNCSC CRS — activity log: who did what, to which shop's data, and when.
--
-- One row per action an administrator may need to account for: a day sheet
-- created or changed, a receipt, an inspection, a month closed, a clear
-- requested / approved / rejected, a payment raised / submitted / decided, a
-- statement or DSS opened, a user added or transferred, a sign-in.
--
-- TWO DATES, DELIBERATELY. `at` is when the person acted. `entry_date` (or
-- `entry_month` + `entry_year` for month-keyed data) is the date the DATA
-- belongs to. Updating the 1 September sheet on 17 September is one row with
-- at = 17 Sep and entry_date = 1 Sep — the office needs both to know which
-- day's figures moved and when somebody moved them.
--
-- WHO. The person, not the login: a shop's Bill Clerk and Packer share one
-- username, so the user id, full name and role are copied onto the row at the
-- time of the action. A Packer transferred next month still shows under the
-- shop and role they acted as.
--
-- USER OR SYSTEM. When a save re-carries later days' Opening, or a receipt
-- moves a day sheet's figures, those days are logged with source = 'system'
-- and action = 'recalculated', attributed to the person whose action caused
-- it — never as if they had keyed every one of those days by hand.
--
-- WRITTEN ONLY BY ROUTE HANDLERS, on the server, at the moment the data
-- changes — so live sync refreshing a screen never writes a row, and a refused
-- or conflicting save writes none. Append-only: nothing in the app updates or
-- deletes a row.
--
-- Run AFTER 0005_notifications.sql. Until it is run the app keeps working:
-- actions are simply not logged, and the dashboard's Recent Activity falls
-- back to what it derives from crs_state_audit.

create table if not exists activity_log (
  id              bigint      generated by default as identity primary key,
  at              timestamptz not null default now(),
  actor_user_id   bigint,
  actor_username  text        not null default '',
  actor_name      text        not null default '',
  actor_role      text        not null default '',
  source          text        not null default 'user' check (source in ('user', 'system')),
  crs_id          integer,
  shop_name       text        not null default '',
  module          text        not null,
  action          text        not null,
  entry_date      date,
  entry_month     smallint    check (entry_month between 1 and 12),
  entry_year      smallint,
  -- The store key or record id the action touched: '7_2026-09-16', a receipt
  -- id, a payment order id.
  record_key      text,
  summary         text        not null default '',
  -- [{ "label": "BRA Rice · Sales", "before": "100", "after": "150" }, …]
  changes         jsonb       not null default '[]'::jsonb,
  -- A clear request or payment order this row belongs to.
  related_id      text
);

-- The log page: newest first, within a date range, optionally one shop / one
-- person / one module.
create index if not exists activity_log_at_idx     on activity_log (at desc, id desc);
create index if not exists activity_log_crs_idx    on activity_log (crs_id, at desc);
create index if not exists activity_log_actor_idx  on activity_log (actor_user_id, at desc);
create index if not exists activity_log_module_idx on activity_log (module, action, at desc);
create index if not exists activity_log_entry_idx  on activity_log (crs_id, entry_date);

comment on table activity_log is 'Who did what to which shop''s data, and when. Written only by route handlers; read only by administrators.';
comment on column activity_log.at is 'When the person acted.';
comment on column activity_log.entry_date is 'The date the data belongs to — not when it was changed.';
comment on column activity_log.source is 'user = the person did this; system = recalculated because of what they did.';

-- Same posture as every table in this schema: RLS on, no permissive policy,
-- every read and write through route handlers holding the secret key. The
-- all-shop log is served only to administrators (/api/activity/log).
alter table activity_log enable row level security;

notify pgrst, 'reload schema';
