-- TNCSC CRS — the statement PDFs uploaded for the Manual 3-Month PV.
--
-- Reports → Quarterly PV → Manual reads a past month from the office's own
-- statement PDFs (CRS PAGE2, GUNNY, CRS POLICE — pvPdfParse.ts). Until now the
-- pages read from them lived only in the browser tab (sessionStorage), so a
-- new tab, another computer or signing in again showed every month as never
-- uploaded and the office uploaded the same files again (office, 2026-10-06).
--
-- ONE ROW PER FILE, the month's ACTIVE set being every row for that
-- (crs_id, year, month). A month may hold several files (PAGE2 and GUNNY as
-- separate PDFs). "Replace PDF" inserts the new file(s) and then deletes the
-- month's other rows, so there is never a second active set and no history is
-- kept. The same file (sha256) twice in one month is stored once.
--
-- The PDF itself is kept (base64 text): Generate reads the SAVED files every
-- time, so a replaced PDF is what the next PV is built from — never a copy
-- cached in a browser.
--
-- Isolated by shop: every read and write is filtered by crs_id in the route
-- handler (/api/pv-uploads), and a shop user may only reach their own shop.
--
-- Run AFTER 0008_activity_log_complete.sql. Until it is run the Manual PV
-- says the uploads cannot be saved and saves nothing.

create table if not exists pv_upload_files (
  id                bigint      generated by default as identity primary key,
  crs_id            integer     not null check (crs_id between 1 and 99),
  year              smallint    not null,
  month             smallint    not null check (month between 1 and 12),
  -- '2026-27' — the financial year the month belongs to.
  fy                text        not null,
  file_name         text        not null,
  file_size         integer     not null check (file_size > 0),
  sha256            text        not null,
  data_b64          text        not null,
  uploaded_at       timestamptz not null default now(),
  uploaded_by_id    bigint,
  uploaded_by_name  text        not null default ''
);

create index if not exists pv_upload_files_month_idx on pv_upload_files (crs_id, year, month);

-- Same posture as every table here: RLS on, no permissive policy; only route
-- handlers holding the secret key read or write it.
alter table pv_upload_files enable row level security;
revoke all on table pv_upload_files from anon, authenticated;

notify pgrst, 'reload schema';
